### ISSUE TITLE
Somehow \r is in the file

### ISSUE THREAD

**Issue by 0blu** [janispritzkau/minecraft-reverse-proxy#1]
Hey,
I've installed your tool with `npm i -g mcrevproxy`
on node `v8.10.0 / Ubuntu 18.04`
but it seems that when I try to execute it, it complains about the `\r` in the header of the file.

Did you upload it to npm via a Windows machine?

Quick proof:
```
> grep $'\r' `which mcrevproxy` | wc -l
92
```

**Comment by janispritzkau** [comment]
Thanks for reporting. I reuploaded it with LF endings. I normally use Linux. I still worked on my system, maybe it had to do with package versions.
